//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirTicket.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Bearer T1RLAQJBdhXbg+kLXH7xq0GZh9FyL+1RIBC1XyFzf/T0hsCblWj+WvlDAACw3ZZqYcNcxS5NWqqvXFCOm4AUP3+XAvJIErS3XxYZS+ShlxbSEYcX1nKGp2IbBbSzBSaRTpgOTymBQisUFRn4s6+ChH0xq1DFBaUzeIZOU26gkUnfin/96Dlc9MARp+L7pPZxET+O+lNRoM9Uy02YXxVVkEVs9Euc4dGaLSWMvLjnwLEkjM0lKHoSxSt7TyPeer83vuVjNgO1L1xKk1ASkmxMFVb82Hdp3nxVOdPRZbo*")]
        public string vnAirToken {
            get {
                return ((string)(this["vnAirToken"]));
            }
            set {
                this["vnAirToken"] = value;
            }
        }
    }
}
