//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirTicket
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public long id { get; set; }
        public Nullable<long> calendar_id { get; set; }
        public Nullable<int> airline_id { get; set; }
        public Nullable<int> price1 { get; set; }
        public Nullable<byte> status { get; set; }
        public Nullable<int> tax { get; set; }
        public Nullable<int> total { get; set; }
        public Nullable<int> from_id { get; set; }
        public Nullable<int> to_id { get; set; }
        public Nullable<int> passenger_id { get; set; }
    }
}
